set(_CATKIN_CURRENT_PACKAGE "steer")
set(steer_VERSION "0.0.0")
set(steer_MAINTAINER "root <root@todo.todo>")
set(steer_PACKAGE_FORMAT "2")
set(steer_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(steer_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(steer_BUILDTOOL_DEPENDS "catkin")
set(steer_BUILDTOOL_EXPORT_DEPENDS )
set(steer_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(steer_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(steer_TEST_DEPENDS )
set(steer_DOC_DEPENDS )
set(steer_URL_WEBSITE "")
set(steer_URL_BUGTRACKER "")
set(steer_URL_REPOSITORY "")
set(steer_DEPRECATED "")